#ifndef LIBFT_H
# define LIBFT_H

# define LIBFT_ALPHA_LOW 'A'
# define LIBFT_ALPHA_HIGH 'z'

# define LIBFT_DIGIT_LOW '0'
# define LIBFT_DIGIT_HIGH '9'

//TODO CHECKEN OF DEZE KLOPPEN (ZIJN OCTALS);
# define LIBFT_ASCII_LOW 0
# define LIBFT_ASCII_HIGH 0177

# define LIBFT_PRINTABLE_LOW 040
# define LIBFT_PRINTABLE_HIGH 0176
#endif